### ISSUE TITLE
I am facing gradle sync issue

### ISSUE THREAD

**Issue by raviteja06** [raveeshbhalla/Pacemaker#1]

**Comment by raveeshbhalla** [comment]
Can you please share your build.gradle file here

**Comment by raviteja06** [comment]
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.0'
    compile 'com.android.support:recyclerview-v7:22.2.0'
    compile 'com.jakewharton:butterknife:6.1.0'
    compile 'ch.acra:acra:4.6.2'
    compile 'com.google.android.gms:play-services-gcm:7.5.0'
    compile 'com.google.android.gms:play-services-maps:7.5.0'
    compile 'com.google.android.gms:play-services-location:7.5.0'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'de.halfbit:tinybus:3.0.1'
    compile 'com.mcxiaoke.volley:library:1.0.17'
    compile 'com.rengwuxian.materialedittext:library:2.1.4'
    compile('com.github.nkzawa:socket.io-client:0.5.2') {
        exclude group: 'org.json', module: 'json'
    }
    compile 'in.raveesh:pacemaker:0.1.0-SNAPSHOT'
    compile 'com.intuit.sdp:sdp-android:1.0.0'
    compile('de.keyboardsurfer.android.widget:crouton:1.8.5@aar') {
        exclude group: 'com.google.android', module: 'support-v4'
    }
    compile 'com.mixpanel.android:mixpanel-android:4.6.2'
}

error 
Error:(86, 13) Failed to resolve: in.raveesh:pacemaker:0.1.0-SNAPSHOT
<a href="openFile">Show in File</a><br><a href="open.dependency.in.project.structure">Show in Project Structure dialog</a>

**Comment by raveeshbhalla** [comment]
Have you added the following line to get Snapshot repositories, as mentioned in the readme?

```
repositories {
    maven { url "https://oss.sonatype.org/content/repositories/snapshots/" }
}
```

**Comment by raviteja06** [comment]
Thanks. My Bad.
